/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemonitoringsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 2ndyrGroupA
 */
public class UserAttendanceForm extends javax.swing.JFrame {

    /**
     * Creates new form UserAttendanceForm
     */
    public UserAttendanceForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emp_no = new javax.swing.JTextField();
        timeout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        timein = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 360));
        setPreferredSize(new java.awt.Dimension(400, 395));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_no.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        emp_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_noActionPerformed(evt);
            }
        });
        getContentPane().add(emp_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 40));

        timeout.setText("TIME OUT");
        timeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeoutActionPerformed(evt);
            }
        });
        getContentPane().add(timeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE NO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 30));

        timein.setText("TIME IN");
        timein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeinActionPerformed(evt);
            }
        });
        getContentPane().add(timein, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ATTENDANCE FORM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 270, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java images/user_attendance2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_noActionPerformed
        
    }//GEN-LAST:event_emp_noActionPerformed

    private void timeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeinActionPerformed
       String employee_no = emp_no.getText();
       try{
            
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancemsfjava", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            String employee = "SELECT e.employee_no,concat(e.firstname,' ',e.middlename,' ',e.lastname) as name FROM employee e WHERE employee_no = '"+employee_no+"'";
            ResultSet result = stmt.executeQuery(employee);
            
            if(result.next()){
                String fullname = result.getString("name");
                System.out.println("fullname: "+fullname);
                String query = "INSERT INTO attendance (employee_no,fullname,log_type) VALUES ('"+employee_no+"','"+fullname+"','1')"; 
                stmt.executeUpdate(query); 
                JOptionPane.showMessageDialog(null, "You're time in has been recorded");
                emp_no.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Employee No ","Alert", JOptionPane.WARNING_MESSAGE);
                emp_no.setText("");
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Alert", JOptionPane.WARNING_MESSAGE);
            emp_no.setText("");
        }
    }//GEN-LAST:event_timeinActionPerformed

    private void timeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeoutActionPerformed
            String employee_no = emp_no.getText();
       try{
            
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancemsfjava", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            String employee = "SELECT e.employee_no,concat(e.firstname,' ',e.middlename,' ',e.lastname) as name FROM employee e WHERE employee_no = '"+employee_no+"'";
            ResultSet result = stmt.executeQuery(employee);

            if(result.next()){
                String fullname = result.getString("name");
 
                String query = "INSERT INTO attendance (employee_no,fullname,log_type) VALUES ('"+employee_no+"','"+fullname+"','2')"; 
                stmt.executeUpdate(query); 
                JOptionPane.showMessageDialog(null, "You're time out has been recorded");
                emp_no.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect Employee No ","Alert", JOptionPane.WARNING_MESSAGE);
                emp_no.setText("");
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Alert", JOptionPane.WARNING_MESSAGE);
            emp_no.setText("");
        }
    }//GEN-LAST:event_timeoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAttendanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emp_no;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton timein;
    private javax.swing.JButton timeout;
    // End of variables declaration//GEN-END:variables
}
